### ISSUE TITLE
Define RATS and SCITT Terminology mapping

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-scitt/draft-birkholz-scitt-architecture#40] opened 2022-11-21 18:08 UTC
This issue deals with documenting overlap between SCITT and RATS Terminology and identifying core differences

**Comment by letmaik** [comment] 2022-11-23 10:06
Duplicate of https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/37.

**Closed as completed by letmaik** 2022-11-23 10:06 UTC
