### ISSUE TITLE
Language mapping and terms.

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/draft-birkholz-scitt-architecture#24] opened 2022-09-26 15:53 UTC
On the call reviewing: [IETF RATs Overview](https://1drv.ms/p/s!Aqj-Bj9PNivcn5kVtfsMUnMGtLTtyg?e=9FDPFh)

![Screen Shot 2022-09-26 at 10 51 47 AM](https://user-images.githubusercontent.com/8295856/192323088-b079a660-2b9f-4886-879c-b80a4bd2d9aa.png)

Orie said:

> In W3C VCs “Issuers" produce both “attestations (claims in their words) and evidence (evidence in their words).

Orie said:

> I think a “SCITT Notary" is a "RATs Verifier”

Monty said:

> I would think SCITT defining the distribution of Reference Values (RV) in the RATS model. The Notary "certifies" that the RV is valid. Verifiers take as input (as shown on slide 6) the RVs from SCITT.

Henk said:

> In "RATS round 1", the registry (replicated nodes) take on the role of Attester, I think
> In "RATS round 2", the issuers take on the role of Attester, I think

**Comment by SteveLasker** [comment] 2022-10-12 21:34
Steve said, "RATS, there's a lot of terminology to review and consolidate" :)

**Comment by yogeshbdeshpande** [comment] 2023-02-21 15:48
@OR13, this is a duplicate of RATS and SCITT Overlap of terminologies: We plan to close this

**Comment by SteveLasker** [comment] 2023-02-21 15:51
Closing as this should be covered by" https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/37

**Closed as completed by SteveLasker** 2023-02-21 15:51 UTC
